import styles from './ContentSections.module.css';

export function CateringOverview() {
  return (
    <section className={styles.section} id="catering-landscape">
      <h2>The 2026 Catering Landscape</h2>
      <p>Applebee's is globally recognized for its vibrant dine-in atmosphere and late-night bar culture. However, operating silently behind the scenes of the bustling dining room is a massive, high-volume Business-to-Business (B2B) catering operation. In 2026, the demand for affordable, crowd-pleasing food for corporate events, family reunions, and holiday parties has driven Applebee's to engineer a highly efficient off-premise catering model.</p>

      <p>When you place a catering order for 100 people, you are not simply ordering 100 individual meals. You are tapping into a specialized logistical network designed to produce massive yields of food simultaneously, package them in insulated thermal containers, and coordinate delivery windows with pinpoint accuracy.</p>

      <p>This 3,000-word comprehensive guide strips away the marketing fluff to explain the strict mechanics of Applebee's catering. We will break down the aggressive "$10 Per Person" economic strategy, the physical science behind their thermal packaging, the brutal reality of kitchen lead times, and how office managers can successfully execute tax-exempt orders through third-party platforms like ezCater.</p>
    </section>
  );
}

export function EconomicModel() {
  return (
    <section className={styles.section} id="economic-model">
      <h2>The "$10 Per Person" Economic Model</h2>
      <p>The single greatest advantage Applebee's holds in the highly competitive catering sector is aggressive volume pricing. While upscale fast-casual brands (like Panera or Chipotle) frequently push catering costs to $15 or $20 per head, Applebee's has mathematically engineered its party platters to hit a highly coveted <strong>$10 to $12 per person</strong> price point.</p>

      <h3>How the Math Works</h3>
      <p>A standard Applebee's Party Platter is explicitly designed to serve 6 to 8 adult guests. When an office manager orders a massive tray of Three-Cheese Chicken Penne paired with a tray of House Salad, the total cost distributed across the headcount drops significantly. This allows corporate event planners to feed massive crowdssuch as a 200-person warehouse shift or a 50-person high school sports banquetwithout triggering budget audits from their finance departments.</p>

      <h3>The Loss Leader Strategy</h3>
      <p>Applebee's achieves this price point by heavily leveraging pasta and rice-based dishes in their catering lineup. The incredible profit margins generated by a tray of Mac & Cheese effectively subsidize the high food costs of the Double-Glazed Baby Back Ribs platters, creating a blended profit margin that keeps franchise owners happy while providing immense value to the consumer.</p>
    </section>
  );
}

export function MenuBreakdown() {
  return (
    <section className={styles.section} id="menu-breakdown">
      <h2>Menu Breakdown: The Party Platters</h2>
      <p>A catering menu is fundamentally different from a dine-in menu. Items that degrade rapidly (like a medium-rare Ribeye steak or crispy French fries) are intentionally removed from the catering lineup. Instead, the menu focuses on braised meats, heavy sauces, and pastafoods that maintain their structural integrity and heat when stored in bulk containers.</p>

      <h3>The Appetizer Trays</h3>
      <p>The cornerstone of the Applebee's catering experience. These trays are ubiquitous at Super Bowl parties and office happy hours:</p>
      <ul>
        <li><strong>Boneless Wings Platter:</strong> Contains approximately 60 to 70 massive pieces of double-breaded chicken breast, served with bulk containers of Honey BBQ or Buffalo sauce and a literal pint of Bleu cheese dressing.</li>
        <li><strong>Spinach & Artichoke Dip:</strong> Delivered in a half-pan (a massive aluminum tray) alongside a massive bag of freshly fried tortilla chips.</li>
      </ul>

      <h3>The Entrée Trays</h3>
      <p>Designed for heavy, fork-and-knife dining:</p>
      <ul>
        <li><strong>Fiesta Lime Chicken Platter:</strong> 8 to 10 massive chicken breasts, grilled, sliced, and shingled across a bed of cilantro rice, smothered in melted cheese and Mexi-ranch.</li>
        <li><strong>Four-Cheese Mac & Cheese with Honey Pepper Chicken:</strong> The single most calorie-dense and universally beloved item on the catering menu. It holds heat exceptionally well, making it the perfect anchor for a buffet line.</li>
      </ul>
    </section>
  );
}

export function TwoHourNotice() {
  return (
    <section className={styles.section} id="two-hour-notice">
      <h2>The "Two-Hour Notice" Reality</h2>
      <p>One of the most heavily advertised features of Applebee's catering is the claim that they can fulfill orders with merely "Two Hours of Notice." While this looks fantastic on a marketing brochure, relying on this claim is a massive logistical gamble.</p>

      <h3>The Kitchen Capacity Limit</h3>
      <p>If you call an Applebee's at 10:00 AM on a random Tuesday and ask for three trays of Boneless Wings for Noon, the kitchen can easily accommodate you. The prep cooks are already in the building, and the fryers have excess capacity. </p>
      <p>However, if you attempt to place a $500 catering order at 5:00 PM on a Friday with two hours of notice, your order will almost certainly be rejected by the General Manager. A Friday night dinner rush requires 100% of the kitchen's grill and fryer space just to feed the dine-in guests. Injecting a massive catering order into that ecosystem will instantly crash the kitchen, resulting in cold food and furious dine-in customers.</p>

      <h3>The 24-Hour Rule</h3>
      <p>To guarantee fulfillment and ensure the absolute highest food quality, you must provide <strong>at least 24 hours of notice</strong>. This allows the General Manager to artificially increase the daily food truck order to ensure they don't run out of chicken breasts, and it allows them to schedule an extra prep cook specifically to handle your platters.</p>
    </section>
  );
}

export function DeliveryPickup() {
  return (
    <section className={styles.section} id="delivery-pickup">
      <h2>Delivery vs. Pickup: The ezCater Integration</h2>
      <p>The biggest logistical hurdle in catering is the final mile: transporting 50 pounds of hot food from the Applebee's kitchen to a 12th-floor corporate boardroom.</p>

      <h3>The End of In-House Delivery</h3>
      <p>Historically, an Applebee's manager would load the food into their personal SUV and drive it to your office. In 2026, due to massive liability and insurance costs, almost zero Applebee's locations offer direct, in-house delivery. If you call the restaurant directly, they will mandate that you physically pick up the food via Carside To Go.</p>

      <h3>The ezCater Solution</h3>
      <p>To solve the B2B delivery problem, Applebee's has heavily integrated with third-party corporate catering logistics platforms, most notably <strong>ezCater</strong>. When you order Applebee's through ezCater, the platform dispatches a professional, vetted catering courier. These couriers possess the massive insulated bags required to transport half-pans, and they are trained to physically bring the food into your building and set up the buffet line. This convenience comes at a premium, as ezCater orders typically include a delivery fee and an expected courier tip.</p>
    </section>
  );
}

export function PackagingScience() {
  return (
    <section className={styles.section} id="packaging">
      <h2>Packaging & Temperature Control</h2>
      <p>The defining metric of a successful catering event is temperature. If a tray of Three-Cheese Chicken Penne arrives at a corporate office lukewarm (below 135°F), the food is not only unappetizing but potentially dangerous due to bacterial growth.</p>

      <h3>The Thermal Architecture</h3>
      <p>Applebee's utilizes heavy-duty, injection-molded polypropylene (PP) half-pans with securely snapping lids. Unlike cheap aluminum foil trays that immediately bleed heat, these PP containers possess superior thermal retention properties. Furthermore, when an order is packaged, the hot trays are stacked together and immediately sealed inside thick, reusable insulated catering bags.</p>

      <h3>The Venting Dilemma</h3>
      <p>For fried items (like Boneless Wings or Mozzarella Sticks), the packaging creates a paradoxical problem: trapping heat also traps steam, which instantly destroys the crispy breading. To combat this, the lids for fried platters are strategically vented. This allows just enough moisture to escape to maintain the structural crunch, while retaining enough ambient heat to keep the chicken warm during transit.</p>
    </section>
  );
}

export function SternoGuide() {
  return (
    <section className={styles.section} id="sterno-guide">
      <h2>The Sterno & Chafing Dish Setup Guide</h2>
      <p>If your event is going to last longer than 45 minutes, relying on the plastic catering containers is a recipe for disaster. The food will go cold before the CEO finishes their opening remarks. To execute a professional event, you must transfer the Applebee's food into standard wire chafing dishes powered by Sterno fuel cans.</p>

      <h3>The Professional Transfer</h3>
      <ol>
        <li><strong>Procure Equipment:</strong> Purchase standard wire chafing racks, full-size aluminum water pans, half-size aluminum food pans, and 2-hour gel Sterno cans (available at any party supply store).</li>
        <li><strong>The Water Bath:</strong> Place the wire rack on the table. Drop the full-size water pan into the rack. Fill it with exactly one inch of hot tap water. This creates the steam bath that gently warms the food without burning the bottom.</li>
        <li><strong>Ignite the Fuel:</strong> Pop the caps off two Sterno cans and place them directly under the water pan. Ignite them with a long lighter.</li>
        <li><strong>The Transfer:</strong> Do not place the Applebee's plastic containers over the fire; they will melt and ruin the food. Instead, carefully slide the hot Applebee's food into the half-size aluminum food pans, and drop those into the steaming water bath.</li>
      </ol>
      <p>With this setup, a tray of Fiesta Lime Chicken will remain at a perfect, food-safe 150°F for up to two hours.</p>
    </section>
  );
}

export function CorporateTax() {
  return (
    <section className={styles.section} id="corporate-tax">
      <h2>Corporate Accounts & Tax Exemption</h2>
      <p>For non-profit organizations, schools, and government entities, paying the 8% to 10% local sales tax on a massive $1,000 catering order is a severe budget drain. Applebee's is fully equipped to process tax-exempt B2B orders, but it requires strict adherence to bureaucratic procedure.</p>

      <h3>The Physical Certificate Rule</h3>
      <p>If you are picking up the order directly from the restaurant, you cannot simply tell the manager that your organization is tax-exempt. The POS system legally requires the manager to input a specific tax ID. You must physically bring a printed copy of your state-issued <strong>Tax Exemption Certificate (e.g., a 501(c)(3) form)</strong> and hand it to the manager. They will photocopy the certificate and attach it to the physical receipt for their franchise accounting department.</p>

      <h3>The Third-Party Loophole</h3>
      <p>If you order through ezCater, you do not deal with the restaurant's tax protocol. Instead, you upload your tax exemption certificate directly to your ezCater corporate account profile. The platform will automatically strip the sales tax from your Applebee's checkout screen, streamlining the entire process for office administrators.</p>
    </section>
  );
}

export function EventSpecificOrdering() {
  return (
    <section className={styles.section} id="event-ordering">
      <h2>Event Specific Ordering Strategies</h2>
      <p>Ordering the correct ratio of food is an art form. The type of event you are hosting drastically alters the required menu composition.</p>

      <h3>The Corporate Office Lunch</h3>
      <p>Office workers sitting at desks do not want messy, sauce-covered ribs. They require clean, fork-friendly options. The optimal order for a 20-person office meeting is two trays of Three-Cheese Chicken Penne, one massive House Salad tray with dressing on the side, and a platter of Club Sandwiches cut into quarters. This prevents messy keyboards and stained dress shirts.</p>

      <h3>The Super Bowl / Tailgate Party</h3>
      <p>A sporting event demands aggressive, high-protein finger foods. Plates and forks should be optional. For a 20-person tailgate, abandon the salads entirely. Order three massive trays of Boneless Wings (one Hot, one Honey BBQ, one Garlic Parm), a tray of Mozzarella sticks, and a tray of Double-Glazed Baby Back Ribs. Ensure you request an excess supply of wet naps.</p>
    </section>
  );
}

export function CateringFAQ() {
  const faqData = [
    { question: "How many people does an Applebee's catering tray serve?", answer: "A standard Applebee's catering platter (half-pan) is designed to serve 6 to 8 adult guests. If you are serving a group of teenagers or athletes, you should assume the tray will only serve 4 to 5 people." },
    { question: "Does Applebee's deliver catering orders?", answer: "Generally, no. Most Applebee's locations require you to pick up catering orders via Carside To Go. However, you can secure professional delivery and setup by ordering Applebee's catering through third-party corporate platforms like ezCater." },
    { question: "Do catering orders include plates and silverware?", answer: "Yes, but you must explicitly request them. When placing your order, ask the manager to include 'Setup Supplies,' which will provide you with disposable plates, plastic cutlery sets, napkins, and serving tongs at no additional charge." },
    { question: "Can I cancel an Applebee's catering order?", answer: "Yes, but timing is critical. Because the restaurant orders bulk inventory specifically for your event, you must typically cancel at least 24 hours in advance to receive a full refund. Canceling two hours before the event will usually result in a 50% to 100% penalty charge." },
    { question: "How do I keep Applebee's catering hot?", answer: "The provided plastic containers will hold heat for about 30 to 45 minutes. For longer events, you must transfer the food into aluminum pans and place them in a wire chafing dish rack suspended over a hot water bath heated by Sterno cans." }
  ];

  const schemaData = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqData.map(faq => ({
      "@type": "Question",
      "name": faq.question,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.answer
      }
    }))
  };

  return (
    <section className={styles.section} id="faq">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaData) }}
      />
      <h2>Frequently Asked Questions: Applebee's Catering</h2>
      <div className={styles.faqList}>
        {faqData.map((faq, index) => (
          <article key={index} className={styles.faqItem}>
            <h3>{faq.question}</h3>
            <p>{faq.answer}</p>
          </article>
        ))}
      </div>
    </section>
  );
}
